name: ct_flutter_integration
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  clevertap_plugin: 1.1.4

  firebase_messaging: ^7.0.0

  flutter_local_notifications: ^1.4.4+2

  intl: ^0.16.1

  flutter_windowmanager: ^0.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.9.0

flutter:
  uses-material-design: true

module:
  androidX: true